export const CHANGE_LOCATION = "CHANGE_LOCATION";
export type CHANGE_LOCATION = typeof CHANGE_LOCATION;

export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const RECEIVE_EVENTS = "RECEIVE_EVENTS";
